name: build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version:
        - 14.x
        os:
        - macos-latest
        - windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: update npm
      run: npm install npm@8.6.x -g

    - name: update npm
      run: npm install -g node-gyp@8.4.x

    - name: install
      run: npm install @mapbox/node-pre-gyp@1.0.9 -g

    - name: npm-install
      run: npm install --ignore-scripts

    - name: build
      run: node-pre-gyp install --build-from-source

    - name: test
      run: npm run test

    - name: pack
      run: node-pre-gyp package

    - uses: actions/upload-artifact@v2
      with:
        name: build
        path: build
